FROM maven:3.9.4-eclipse-temurin-17
WORKDIR /workspace
COPY pom.xml ./
RUN mvn -q -DskipTests dependency:go-offline
VOLUME ["/workspace"]
EXPOSE 8080
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Dspring.output.ansi.enabled=never"]
